version: "3.7"

services:
    nginx:
        build:
            context: ./nginx
        volumes: 
            - ../src:/var/www
        ports:
            - "80:80"
            - "443:443"
    php:
        build:
            context: ./php
        volumes:
            - ../src:/var/www
        ports:
            - "8000:8000"
            - "9000:9000"
    mariadb:
        build:
            context: ./mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
    redis:
        build:
            context: ./redis
        ports:
            - "6379:6379"